# fly.toml app configuration file generated for react-socket-server on 2023-05-17T17:32:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "react-socket-server"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
